# Generated by Django 3.1.5 on 2021-02-09 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210209_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='date_added',
        ),
    ]
